### ISSUE TITLE
correction of adducts.tsv file

### ISSUE THREAD

**Issue by DennisJakob** [kbseah/mass2adduct#3]
Hi Brandon,
there are small issues in kbseah/mass2adduct/data-raw/adducts.tsv
--> same issues in the adducts2.tsv

1. Na adduct | Na-H | 21.983120
--> should be Na adduct | Na-H | 21.981945
2. Silver | Ag | 105.89730
--> Silver | Ag-H | 105.89730
3. Phosphate | HPO3 | 79.96633
--> Phosphate | PO3 | 78.958508
4. Pyrophosphate | PP | 61.94753
--> Pyrophosphate | P2O7 | 173.911931

Would be great if you could correct that.
Cheers Dennis.

**Comment by kbseah** [comment]
Fixed in commit 0094da5
