### ISSUE TITLE
cardinal2msimat() compatibility with Cardinal 3.0.1

### ISSUE THREAD

**Issue by goterm** [kbseah/mass2adduct#5]
hello,
I process my .imzml file with Cardinal  3.0.1:

**d_peaks <- mydata %>% 
  normalize(method="rms") %>% #tic or rms
  smoothSignal() %>% 
  reduceBaseline() %>% 
  peakBin(ref=mz(mydata_ref), #mydata_ref
          tolerance=0.5,
          units="mz") %>%
  process()**

and when running the command:

**d_msimat <- cardinal2msimat(d_peaks)**

it returns:
**Error in if (class(spectra(d)) == "matrix") { : 
  the condition has length > 1**
I believe it happens because
**(class(spectra(d_peaks)))** contains also array (**[1] "matrix" "array"**).

any hints on how to fix this?
thanks!

**Comment by kbseah** [comment]
Thanks for reporting this issue.

It's possible that Cardinal made a backwards-incompatible change with major version 3. We originally developed this to work with Cardinal v2.2.6. Would it be possible for you to try again with the older version of Cardinal?

**Comment by goterm** [comment]
thanks for the very fast feedback!
I just fixed by changing the cardinal2msimat if clause:

**cardinal3msimat <- function (d) 
{
  if ("peakBin" %in% names(d@processing)) {
    if (class(spectra(d))_[1]_ == "matrix") 
...**

thanks again!

**Comment by kbseah** [comment]
Thanks for sharing the fix!

**Comment by kailaw138** [comment]
Thanks, I have created a function cardinal3msimat as goterm suggested, but got an error. Could you please direct me to make it work?

# load packages
library(Cardinal)
library(mass2adduct)

# Read ImzML file
d <- readImzML(name = "test_POS", folder = "D:/Dataset1/")
peaklist <- c(826.572, 844.525, 872.557) # <- peak list of known molecular ions
d_peaks <- d %>% 
  normalize() %>% 
  smoothSignal() %>% 
  reduceBaseline() %>% 
  peakBin(ref = peaklist) %>%
  process(BPPARAM = SnowParam(progressbar = TRUE))

# Convert to msimat format for mass2adduct

cardinal3msimat <- function (d_peaks)
{
  if ("peakBin" %in% names(d_peaks@processing)) {
    if (class(spectra(d_peaks))[1] == "matrix") {
      # Extract peak matrix and coordinates
      peak_matrix <- spectra(d_peaks)
      coords <- coordinates(d_peaks)
      # Create data frame with peak matrix and coordinates
      df <- cbind(peak_matrix, coords)
      # Return data frame as msimat object
      return(msimat(df))
    } else {
      stop("Spectra must be a matrix")
    }
  } else {
    stop("Data must be peak binned")
  }
}

d_msimat <- cardinal3msimat(d_peaks) 

=======================================

> d_msimat <- cardinal3msimat(d_peaks)  

Error in read.table(file = file, header = header, sep = sep, quote = quote, :
'file' must be a character string or connection

**Comment by kailaw138** [comment]
oooh i see... 

# Create a new function cardinal3msimat to substitute cardinal2msimat in the original code
cardinal3msimat <- function (d_peaks)  
{
  if ("peakBin" %in% names(d_peaks@processing)) {
    if (class(spectra(d_peaks))[1] == "matrix") { 
      # Initialize vectors for containing data
      peaks <- mz(d_peaks) # Binned mass values
      spots <- 1:dim(d_peaks)['Pixels'] # Pixel name values
      data <- t(spectra(d_peaks))
      peakintensities <- colSums(data)
      # Store as list and declare class as msimat
      out <- list(mat=as.matrix(data),
                  peaks=as.numeric(peaks),
                  spots=spots,
                  peakintensities=peakintensities)
      class(out) <- "msimat"
      # Return msimat object
      return(out)
    } else {
      stop("Matrix not stored internally as sparse_matc, which should be the case for MSProcessedImagingExperiment")
    }
  } else {
    stop("Only applicable to binned data. Please apply peakBin() processing first.")
  }
}

**Comment by kbseah** [comment]
thanks @kailaw138 for sharing the code! If i understand correctly, the cardinal object was of type `MSProcessedImagingExperiment`?
